services:
  app_db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_modelo_1
    ports:
      - "5432:5432"
    # volumes:
    #   - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - app-app_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     app_db:
  #       condition: service_healthy
  #   networks:
  #     - app-app_db

networks:
  app-app_db:
# volumes:
#   .postgres-data:
